language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-4.0
    packages:
    - clang-9
install:
- "[ $CXX = clang++ ] && export CXX=clang++-9 || true"
script:
  - make
