language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -y install lcov

install: 
  - sudo apt-get install -qq g++-9
  - sudo apt-get install -qq gcc-9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  -  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90

script:
  - export CODECOV_TOKEN="56b8d613-ceb7-4fba-99aa-874bcf3b98e3"
  - sh build.sh

after_success:
# Create lcov report
# capture coverage info
  - lcov --capture --directory . --output-file coverage.info --no-external
# filter out system and extra files.
  - lcov --remove coverage.info '/usr/*' '*/libs/*' '*/tests/*' --output-file coverage.info
# output coverage data for debugging
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
